Fixes bug with date serialisation, and git version change from "unstable" to "alpha"
CatenaLogic/JiraCli pull request #11
Opened 2016-10-27 11:06 UTC by dazinator

When calling the jira rest API to get project versions, the ProjectVersion dto that gets serialised from the json has acouple of dates that weren;t being handled correctly and were generating serialisation errors. This wasn't noticed previously as we didn't have these fields populated in Jira until actual issuing a versions as "Released" and entering in a release date.

Also we updated GitVersion which uses "alpha" in the pre-release versions now instead of "unstable". The MegreVersions functionality was explicitly detecting versions with "unstable" in the label to merge, but with this PR it now handled both.

2016-10-27 12:43 UTC, GeertvanHorrik requested changes
Overall great pr, thanks for the fixes. A few small things (see comments). Next time also please don't commit changes to files that aren't really relevant for the change you are proposing (such as sln, packages.config and FodyWeavers).

2016-10-27 12:43 UTC, GeertvanHorrik commented on src/JiraCli/Extensions/JiraExtensions.version.cs
> +    class CustomDateTimeConverter : IsoDateTimeConverter
Move to separate class please

2016-10-27 12:43 UTC, GeertvanHorrik commented on src/JiraCli/Services/Interfaces/IVersionInfoService.cs
> +using System;
Usings inside namespace

2016-10-27 12:43 UTC, GeertvanHorrik commented on src/JiraCli/Services/VersionInfoService.cs
> +                if (!string.IsNullOrWhiteSpace(semVer.Prerelease))
Note sure what the point of this code is. Does this method ever return true?

2016-10-27 21:21 UTC, dazinator commented
> Next time also please don't commit changes to files that aren't really relevant for the change you are proposing (such as sln, packages.config and FodyWeavers).

Yep - sorry, my bad.. it's just because in my fork I ended up adding this as a submodule and building as part of another solution whilst debugging the issue. I'll be more careful next time.

2016-10-27 21:34 UTC, dazinator commented on src/JiraCli/Services/VersionInfoService.cs
> +                if (!string.IsNullOrWhiteSpace(semVer.Prerelease))
Yeah it does.. It returns true if the version has a Prerelease label, and the predicate check against that label returns true. The predicate we pass in, checks that the label starts with "alpha" or "unstable". 

It allows the caller to make an additional assertion against the pre-release label portion of a pre-release version number when the version number passed in is actually a pre-release version.

2016-10-28 09:32 UTC, GeertvanHorrik commented on src/JiraCli/Services/VersionInfoService.cs
> +                if (!string.IsNullOrWhiteSpace(semVer.Prerelease))
Now I see the return prereleaseLabelChecker. I swear yesterday it had an empty { } or I must have been dreaming.

2016-10-28 09:33 UTC, GeertvanHorrik commented on src/JiraCli/Services/VersionInfoService.cs
> +                if (!string.IsNullOrWhiteSpace(semVer.Prerelease))
I double checked, I commented on the wrong line. See IsPreRelease(stringVersion) instead.

2016-10-28 10:09 UTC, dazinator commented on src/JiraCli/Services/VersionInfoService.cs
> +                if (!string.IsNullOrWhiteSpace(semVer.Prerelease))
Haha yep. Will tidy up 😂

2016-11-22 23:52 UTC, GeertvanHorrik commented
@dazinator did you find time to tidy it up or is it already ready to be merged?

2016-11-23 12:08 UTC, dazinator commented
Afraid I haven't had a chance to tidy this up just yet.

2017-07-17 18:20 UTC, dazinator commented
I have adjusted as per the feedback. Should be ready to merge.

2017-07-17 18:22 UTC, GeertvanHorrik commented
Excellent, thanks!

2017-07-17 18:22 UTC, GeertvanHorrik approved these changes

2017-07-17 18:22 UTC, merged

2017-07-17 18:30 UTC, GeertvanHorrik commented
New version will be available in a few minutes.

2017-07-17 18:34 UTC, dazinator commented
Sadly I think the build might fail, apologies. Have submitted a missed commit.

2017-07-17 18:36 UTC, GeertvanHorrik commented
Already fixed it ;-)

2017-07-17 18:38 UTC, dazinator commented
Cheers