Assigns version to parent issue if subtask
CatenaLogic/JiraCli pull request #13
Opened 2017-07-17 18:54 UTC by dazinator

Submitting this as PR. but happy for it to live in my fork only.

When assigning versions to issues in Jira, if the issues is a subtask, this will assign the version to the parent task instead. We needed this because developers were sometimes associating subtasks to their commits, and then closing the subtasks. Jira wouldn't let a version be assigned to a closed subtask - so they were essentially being missed of the release. Now the parent task gets associated in this instance.

2017-07-24 11:57 UTC, GeertvanHorrik requested changes
Please see all the comments.

2017-07-24 11:57 UTC, GeertvanHorrik commented on src/JiraCli/Models/Assignee.cs
> +﻿using Newtonsoft.Json;
Usings inside namespace + missing header

2017-07-24 11:57 UTC, GeertvanHorrik commented on src/JiraCli/Models/AvatarUrls.cs
> +﻿using Newtonsoft.Json;
Usings inside namespace + missing header

2017-07-24 11:57 UTC, GeertvanHorrik commented on src/JiraCli/Models/Fields.cs
> +﻿using Newtonsoft.Json;
Usings inside namespace + missing header

2017-07-24 11:57 UTC, GeertvanHorrik commented on src/JiraCli/Models/IssueKey.cs
> +﻿using System;
Usings inside namespace + missing header

2017-07-24 11:57 UTC, GeertvanHorrik commented on src/JiraCli/Models/IssueKey.cs
> +            if (issueKeyString == null)
Argument.IsNotNull(() => issueKeyString);

2017-07-24 11:57 UTC, GeertvanHorrik commented on src/JiraCli/Models/JiraIssue.cs
> +using JiraCli.Models;
Usings inside namespace

2017-07-24 11:57 UTC, GeertvanHorrik commented on src/JiraCli/Models/JiraIssueType.cs
> +﻿using Newtonsoft.Json;
Usings inside namespace + missing header

2017-07-24 11:57 UTC, GeertvanHorrik commented on src/JiraCli/Models/JiraObjectBase.cs
> +using Newtonsoft.Json;
Usings inside namespace

2017-07-24 11:57 UTC, GeertvanHorrik commented on src/JiraCli/Models/JiraSearchResponse.cs
> +﻿using Newtonsoft.Json;
Usings inside namespace + missing header

2017-07-24 11:57 UTC, GeertvanHorrik commented on src/JiraCli/Models/Status.cs
> +﻿using Newtonsoft.Json;
Usings inside namespace + missing header

2017-07-24 11:57 UTC, GeertvanHorrik commented on src/JiraCli/Services/VersionService.cs
> +                //if (assignParentOfSubtasks)
Remove this code if it's not needed.

2017-07-24 11:57 UTC, GeertvanHorrik commented on src/JiraCli/Models/IssueKey.cs
> +        public static IssueKey Parse(string issueKeyString)
This is very easy to unit-test, care to add some unit tests?

2017-07-24 12:01 UTC, dazinator commented
Cheers.
This using inside namespace is not a convention I am used to, as you can probably tell! Is there some way we can set up VS tooling / project settings etc such that this will be flagged? Should they already be showing as warnings or something - in which case I may have just missed them :-)

2017-07-24 12:05 UTC, GeertvanHorrik commented
The resharper settings should do it automatically for you, but maybe you are not using it. 

I was putting the usings outside the namespaces as well until someone shown me it can actually lead to unexpected runtime issues. Even though this is a rare use-case, I decided that in order to always prevent something, I had to train my mind to put them inside the namespaces. Now I am used to it, but it took me a while ;-)

2017-08-05 12:28 UTC, GeertvanHorrik requested changes

2017-08-05 12:28 UTC, GeertvanHorrik commented on src/JiraCli/Extensions/JiraExtensions.cs
> +                Debug.Write(ex);
Please use Log.Error(ex) instead.

At the top of the class, add this:

private static readonly ILog Log = LogManager.GetCurrentClassLogger();

2017-08-05 12:28 UTC, GeertvanHorrik commented on src/JiraCli/Services/VersionService.cs
> +            //if (string.IsNullOrWhiteSpace(projectVersion.UserReleaseDate))
I think this code can be removed?

2017-08-05 12:29 UTC, GeertvanHorrik commented
Nice additions. Also thanks for updating the packages. While you are at it, can you please add this in FodyWeavers.xml:

```
<Weavers VerifyAssembly="true">
...
</Weavers>
```

2017-09-29 18:49 UTC, GeertvanHorrik commented
Thanks for the additional commit. Can you also make the other changes requested? Then I can merge this PR.

2017-10-03 18:53 UTC, dazinator commented
Yup sorry I will eventually get around to this

2018-09-03 13:05 UTC, GeertvanHorrik approved these changes

2018-09-03 13:07 UTC, merged

2018-09-03 16:50 UTC, dazinator commented
Thanks for merging